#!/usr/bin/env node
// src/cli/setup.ts
// Interactive CLI Setup Wizard for OpenClaw

import * as readline from "readline";
import * as fs from "fs";
import * as path from "path";

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function ask(question: string, defaultVal?: string): Promise<string> {
  const suffix = defaultVal ? ` [${defaultVal}]` : "";
  return new Promise((resolve) => {
    rl.question(`  ${question}${suffix}: `, (answer) => {
      resolve(answer.trim() || defaultVal || "");
    });
  });
}

function choose(question: string, options: string[], defaultIdx = 0): Promise<string> {
  return new Promise((resolve) => {
    console.log(`\n  ${question}`);
    options.forEach((opt, i) => {
      const marker = i === defaultIdx ? "●" : "○";
      console.log(`    ${marker} ${i + 1}. ${opt}`);
    });
    rl.question(`  Pilih (1-${options.length}) [${defaultIdx + 1}]: `, (answer) => {
      const idx = parseInt(answer.trim(), 10) - 1;
      resolve(options[idx] || options[defaultIdx]);
    });
  });
}

async function main() {
  console.log("");
  console.log("  🦞 ══════════════════════════════════════");
  console.log("     OpenClaw Setup Wizard v2.0");
  console.log("  ══════════════════════════════════════════");
  console.log("");
  console.log("  Wizard ini akan membuat file .env untuk");
  console.log("  mengkonfigurasi OpenClaw Reminder Engine.");
  console.log("");

  // ── 1. Database Type ──
  const dbTypeChoice = await choose("Database engine:", [
    "MySQL / MariaDB",
    "PostgreSQL",
    "MongoDB",
  ], 0);

  const dbTypeMap: Record<string, string> = {
    "MySQL / MariaDB": "mysql",
    "PostgreSQL": "postgres",
    "MongoDB": "mongodb",
  };
  const dbType = dbTypeMap[dbTypeChoice] || "mysql";

  const defaultPorts: Record<string, string> = {
    mysql: "3306",
    postgres: "5432",
    mongodb: "27017",
  };

  console.log("");
  console.log("  ─── Koneksi Database ───");

  let dbUri = "";
  let dbHost = "";
  let dbPort = "";
  let dbUser = "";
  let dbPass = "";
  let dbName = "";

  if (dbType === "mongodb") {
    console.log("");
    const useUri = await ask("Gunakan connection URI? (y/n)", "n");
    if (useUri.toLowerCase() === "y") {
      dbUri = await ask("MongoDB URI", "mongodb://localhost:27017");
    } else {
      dbHost = await ask("Host", "localhost");
      dbPort = await ask("Port", defaultPorts[dbType]);
      dbUser = await ask("Username (kosong = tanpa auth)", "");
      dbPass = await ask("Password", "");
    }
    dbName = await ask("Database name", "openclaw");
  } else {
    dbHost = await ask("Host", "localhost");
    dbPort = await ask("Port", defaultPorts[dbType]);
    dbUser = await ask("Username", dbType === "mysql" ? "root" : "postgres");
    dbPass = await ask("Password", "");
    dbName = await ask("Database name", "openclaw");
  }

  // ── 2. Table/Collection ──
  console.log("");
  console.log("  ─── Schema Configuration ───");
  const tableName = await ask("Table/Collection name", "tugas");
  console.log("");
  console.log("  Kolom bisa di-auto-detect. Jika ingin override,");
  console.log("  isi nama kolom. Kosong = auto-detect.");
  console.log("");
  const colTitle    = await ask("  Kolom judul tugas (COL_TITLE)", "");
  const colDeadline = await ask("  Kolom deadline (COL_DEADLINE)", "");
  const colTelegram = await ask("  Kolom telegram channel (COL_TELEGRAM)", "");
  const colNotified = await ask("  Kolom notified flag (COL_NOTIFIED)", "");

  // ── 3. Telegram ──
  console.log("");
  console.log("  ─── Telegram Bot ───");
  console.log("  Buat bot via @BotFather → /newbot");
  const botToken = await ask("Bot Token");

  // ── 4. Scheduler ──
  console.log("");
  console.log("  ─── Scheduler ───");
  const cronChoice = await choose("Interval cek tugas:", [
    "Setiap 1 menit  (* * * * *)",
    "Setiap 5 menit  (*/5 * * * *)",
    "Setiap 15 menit (*/15 * * * *)",
    "Setiap 1 jam    (0 * * * *)",
  ], 1);

  const cronMap: Record<string, string> = {
    "Setiap 1 menit  (* * * * *)": "* * * * *",
    "Setiap 5 menit  (*/5 * * * *)": "*/5 * * * *",
    "Setiap 15 menit (*/15 * * * *)": "*/15 * * * *",
    "Setiap 1 jam    (0 * * * *)": "0 * * * *",
  };
  const cronSchedule = cronMap[cronChoice] || "*/5 * * * *";

  // ── 5. Deadline reminders ──
  const deadlineDays = await ask("Reminder deadline (hari, comma-separated)", "3,1,0");

  // ── 6. Server ──
  const port = await ask("API Server port", "3000");

  // ── Generate .env ──
  const envContent = [
    "# ═══════════════════════════════════════",
    "# OpenClaw Reminder Engine v2.0",
    "# Generated by: openclaw setup",
    `# Date: ${new Date().toISOString()}`,
    "# ═══════════════════════════════════════",
    "",
    "# Database",
    `DB_TYPE=${dbType}`,
    `DB_HOST=${dbHost}`,
    `DB_PORT=${dbPort}`,
    `DB_USER=${dbUser}`,
    `DB_PASS=${dbPass}`,
    `DB_NAME=${dbName}`,
    dbUri ? `DB_URI=${dbUri}` : "# DB_URI=",
    "",
    "# Schema (kosong = auto-detect)",
    `TABLE_NAME=${tableName}`,
    `COL_TITLE=${colTitle}`,
    `COL_DEADLINE=${colDeadline}`,
    `COL_TELEGRAM=${colTelegram}`,
    `COL_NOTIFIED=${colNotified}`,
    "",
    "# Telegram",
    `TELEGRAM_BOT_TOKEN=${botToken}`,
    "",
    "# Scheduler",
    `CRON_SCHEDULE=${cronSchedule}`,
    `DEADLINE_REMIND_DAYS=${deadlineDays}`,
    "",
    "# Server",
    `PORT=${port}`,
  ].join("\n");

  const envPath = path.resolve(process.cwd(), ".env");

  // Backup existing .env
  if (fs.existsSync(envPath)) {
    const backup = envPath + ".backup." + Date.now();
    fs.copyFileSync(envPath, backup);
    console.log(`\n  📦 Backup: ${backup}`);
  }

  fs.writeFileSync(envPath, envContent, "utf-8");

  console.log("");
  console.log("  ✅ File .env berhasil dibuat!");
  console.log("");
  console.log("  ═══════════════════════════════════════");
  console.log("  Langkah selanjutnya:");
  console.log("");

  if (dbType === "postgres") {
    console.log("  📦 Install PostgreSQL driver:");
    console.log("     npm install pg");
    console.log("     npm install -D @types/pg");
    console.log("");
  } else if (dbType === "mongodb") {
    console.log("  📦 Install MongoDB driver:");
    console.log("     npm install mongodb");
    console.log("");
  }

  console.log("  🚀 Jalankan OpenClaw:");
  console.log("     npm run dev");
  console.log("");
  console.log("  🌐 API akan tersedia di:");
  console.log(`     http://localhost:${port}/api/tugas`);
  console.log(`     http://localhost:${port}/api/status`);
  console.log("  ═══════════════════════════════════════");
  console.log("");

  rl.close();
}

main().catch((err) => {
  console.error("Setup failed:", err);
  rl.close();
  process.exit(1);
});
