// src/cli/commands/init.ts
// ─── candalena-claw init ───
// Creates starter environment: .env template, config folder, checks Node version

import * as fs from "fs";
import * as path from "path";
import {
  printBanner,
  printHeader,
  printOk,
  printWarn,
  printFail,
  printLine,
  printBlank,
  printStep,
  brand,
  createSpinner,
  icon,
} from "../ui";

const ENV_TEMPLATE = `# ═══════════════════════════════════════════════════════
# Candalena Claw — Configuration
# Generated by: candalena-claw init
# Date: __DATE__
# ═══════════════════════════════════════════════════════

# Database — choose: mysql | postgres | mongodb
DB_TYPE=mysql
DB_HOST=localhost
DB_PORT=3306
DB_USER=root
DB_PASS=
DB_NAME=

# MongoDB only: connection URI (optional)
# DB_URI=mongodb://user:pass@cluster.mongodb.net/mydb

# Schema mapping (leave empty for auto-detect)
TABLE_NAME=tugas
COL_ID=
COL_TITLE=
COL_DEADLINE=
COL_COURSE=
COL_LECTURER=
COL_SEMESTER=
COL_KELAS=
COL_TELEGRAM=
COL_NOTIFIED=

# Telegram Bot
TELEGRAM_BOT_TOKEN=

# Scheduler (cron expression)
CRON_SCHEDULE=*/5 * * * *

# Deadline reminder — days before deadline (comma-separated)
DEADLINE_REMIND_DAYS=3,1,0

# API Server
PORT=3000
`;

export async function initCommand(): Promise<void> {
  printBanner();
  printHeader("Initializing Project");

  const cwd = process.cwd();
  const spinner = createSpinner("Setting up project structure...");
  spinner.start();

  // ── 1. Check Node version ──
  const nodeVersion = process.version;
  const major = parseInt(nodeVersion.replace("v", ""), 10);

  await sleep(300);
  spinner.stop();

  if (major < 16) {
    printFail(`Node.js ${nodeVersion} detected — requires v16 or later`);
    printLine(brand.muted("Download: https://nodejs.org"));
    printBlank();
    process.exit(1);
  }
  printOk(`Node.js ${nodeVersion}`);

  // ── 2. Create .env ──
  const envPath = path.resolve(cwd, ".env");
  if (fs.existsSync(envPath)) {
    printWarn(".env already exists — skipping");
  } else {
    const content = ENV_TEMPLATE.replace("__DATE__", new Date().toISOString());
    fs.writeFileSync(envPath, content, "utf-8");
    printOk(".env created");
  }

  // ── 3. Create config directory ──
  const configDir = path.resolve(cwd, ".candalena");
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
    fs.writeFileSync(
      path.join(configDir, ".gitkeep"),
      "",
      "utf-8"
    );
    printOk(".candalena/ directory created");
  } else {
    printWarn(".candalena/ already exists — skipping");
  }

  // ── 4. Create logs directory ──
  const logsDir = path.resolve(cwd, "logs");
  if (!fs.existsSync(logsDir)) {
    fs.mkdirSync(logsDir, { recursive: true });
    printOk("logs/ directory created");
  } else {
    printWarn("logs/ already exists — skipping");
  }

  // ── 5. Check for package.json ──
  const pkgPath = path.resolve(cwd, "package.json");
  if (fs.existsSync(pkgPath)) {
    printOk("package.json found");
  } else {
    printWarn("No package.json found — run 'npm init' first");
  }

  // ── Summary ──
  printBlank();
  console.log(
    `  ${icon.sparkle} ${brand.success.bold("Project initialized successfully!")}`
  );
  printBlank();
  printLine(brand.bold("Next steps:"));
  printBlank();
  printStep(1, `${brand.primary("candalena-claw setup")}   ${brand.muted("— Configure database & Telegram")}`);
  printStep(2, `${brand.primary("candalena-claw start")}   ${brand.muted("— Start the engine")}`);
  printBlank();
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}
